export const ERROR_CODE = {
    BACKUP_TRAFFIC_CREATE_FAILED: 'BACKUP_TRAFFIC_CREATE_FAILED',
    BACKUP_TRAFFIC_INVALID: 'BACKUP_TRAFFIC_INVALID',
    BACKUP_TRAFFIC_NOT_FOUND: 'BACKUP_TRAFFIC_NOT_FOUND',
    BACKUP_TRAFFIC_RESTORE_FAILED: 'BACKUP_TRAFFIC_RESTORE_FAILED',
    DB_WRITE_FAILED: 'DB_WRITE_FAILED',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    TRAFFIC_STREAM_LIMIT: 'TRAFFIC_STREAM_LIMIT',
    UNAUTHORIZED: 'UNAUTHORIZED',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE]
