import { ENGINE_AGENT_ERROR_MESSAGE } from '@containers/contracts/engine-error'
import { ERROR_CODE, type ErrorCode } from './error-code'

const API_ERROR_MESSAGE = {
    [ERROR_CODE.API_KEY_CREATE_FAILED]: 'API 키를 생성할 수 없습니다.',
    [ERROR_CODE.API_KEY_LIST_FAILED]: 'API 키를 조회할 수 없습니다.',
    [ERROR_CODE.API_KEY_NOT_FOUND]: 'API 키를 찾을 수 없습니다.',
    [ERROR_CODE.API_KEY_RATE_LIMITED]: 'API key 요청 한도를 초과했습니다.',
    [ERROR_CODE.API_KEY_REVOKE_FAILED]: 'API 키를 폐기할 수 없습니다.',
    [ERROR_CODE.ARCHIVE_ENTRY_LIMIT]: '아카이브 항목 수가 제한을 초과했습니다.',
    [ERROR_CODE.ARCHIVE_ENTRY_TYPE_INVALID]: '아카이브 항목 유형이 올바르지 않습니다.',
    [ERROR_CODE.ARCHIVE_EXPANSION_LIMIT]: '아카이브 압축 해제 크기가 제한을 초과했습니다.',
    [ERROR_CODE.ARCHIVE_INVALID]: '아카이브 형식이 올바르지 않습니다.',
    [ERROR_CODE.ARCHIVE_METADATA_INVALID]: '아카이브 메타데이터가 올바르지 않습니다.',
    [ERROR_CODE.ARCHIVE_METADATA_LIMIT]: '아카이브 메타데이터 크기가 제한을 초과했습니다.',
    [ERROR_CODE.ARCHIVE_METADATA_MISSING]: '아카이브 메타데이터가 누락되었습니다.',
    [ERROR_CODE.ARCHIVE_PATH_INVALID]: '아카이브 경로가 올바르지 않습니다.',
    [ERROR_CODE.ARTIFACT_DIGEST_MISMATCH]: 'artifact digest가 일치하지 않습니다.',
    [ERROR_CODE.ARTIFACT_IN_USE]: '배포가 참조 중인 artifact는 삭제할 수 없습니다.',
    [ERROR_CODE.ARTIFACT_NOT_FOUND]: 'artifact를 찾을 수 없습니다.',
    [ERROR_CODE.ARTIFACT_LIST_FAILED]: 'artifact 목록을 조회할 수 없습니다.',
    [ERROR_CODE.ARTIFACT_MEDIA_TYPE_INVALID]: 'artifact media type이 올바르지 않습니다.',
    [ERROR_CODE.ARTIFACT_NOT_READY]: 'ready artifact를 찾을 수 없습니다.',
    [ERROR_CODE.AUDIT_UNAVAILABLE]: '감사 기록을 조회할 수 없습니다.',
    [ERROR_CODE.AUTH_LOCKED]: '로그인 시도가 많아 잠시 잠겼습니다. 잠시 후 다시 시도해 주세요.',
    [ERROR_CODE.AUTH_RATE_LIMITED]: '로그인 요청 한도를 초과했습니다.',
    [ERROR_CODE.AUTH_REQUIRED]: '로그인이 필요합니다.',
    [ERROR_CODE.BACKUP_CONTROL_FOREIGN_KEY_INVALID]: '백업 control 스냅샷의 외래 키가 올바르지 않습니다.',
    [ERROR_CODE.BACKUP_CONTROL_INVALID]: '백업 control 스냅샷이 올바르지 않습니다.',
    [ERROR_CODE.BACKUP_DIGEST_MISMATCH]: '백업 digest가 일치하지 않습니다.',
    [ERROR_CODE.BACKUP_DISK_INSUFFICIENT]: '백업을 시작할 디스크 여유 공간이 부족합니다.',
    [ERROR_CODE.BACKUP_ENGINE_FAILED]: '백업 중 engine 작업이 실패했습니다.',
    [ERROR_CODE.BACKUP_FAILED]: '백업을 완료할 수 없습니다.',
    [ERROR_CODE.BACKUP_FOREIGN_KEY_INVALID]: '백업 데이터의 외래 키가 올바르지 않습니다.',
    [ERROR_CODE.BACKUP_INCOMPLETE]: '백업이 불완전합니다.',
    [ERROR_CODE.BACKUP_LIST_FAILED]: '백업 목록을 조회할 수 없습니다.',
    [ERROR_CODE.BACKUP_NOT_FOUND]: '백업을 찾을 수 없습니다.',
    [ERROR_CODE.BACKUP_OPERATION_FAILED]: '백업 작업을 완료할 수 없습니다.',
    [ERROR_CODE.BACKUP_RESTORE_IN_PROGRESS]: '백업 복원이 진행 중입니다.',
    [ERROR_CODE.BACKUP_RESTORE_ROLLBACK_FAILED]: '백업 복원 롤백에 실패했습니다.',
    [ERROR_CODE.BACKUP_SCHEMA_MISMATCH]: '백업 스키마가 일치하지 않습니다.',
    [ERROR_CODE.BACKUP_SECRET_NOT_INCLUDED]: '이 백업에는 암호화 마스터 키가 포함되어 있지 않습니다.',
    [ERROR_CODE.BACKUP_SECRET_PASSPHRASE_INVALID]: '백업 키 passphrase가 올바르지 않습니다.',
    [ERROR_CODE.BACKUP_SECRET_UNAVAILABLE]: '백업 키 파일을 읽거나 해석할 수 없습니다.',
    [ERROR_CODE.BACKUP_TRAFFIC_CREATE_FAILED]: '트래픽 백업 생성에 실패했습니다.',
    [ERROR_CODE.BACKUP_TRAFFIC_DIGEST_MISMATCH]: '백업 트래픽 digest가 일치하지 않습니다.',
    [ERROR_CODE.BACKUP_TRAFFIC_RESTORE_FAILED]: '트래픽 백업 복원에 실패했습니다.',
    [ERROR_CODE.BOOTSTRAP_BUSY]: '초기 owner 설정이 진행 중입니다.',
    [ERROR_CODE.BOOTSTRAP_COMPLETE]: '초기 owner 설정이 이미 완료되었습니다.',
    [ERROR_CODE.CHUNK_DIGEST_MISMATCH]: 'chunk digest가 일치하지 않습니다.',
    [ERROR_CODE.CHUNK_SIZE_INVALID]: 'chunk 크기가 올바르지 않습니다.',
    [ERROR_CODE.CONFIRMATION_MISMATCH]: '대상 확인 문자열이 일치하지 않습니다.',
    [ERROR_CODE.CONTAINER_INSPECT_FAILED]: '컨테이너 상세 상태를 조회할 수 없습니다.',
    [ERROR_CODE.CONTAINER_LOGS_FAILED]: '컨테이너 로그를 조회할 수 없습니다.',
    [ERROR_CODE.CONTROL_FAILED]: 'Docker 작업을 완료할 수 없습니다.',
    [ERROR_CODE.CONTROL_PLANE_STATUS_FAILED]: 'control plane 상태를 조회할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_CONFIGURATION_UNRESOLVED]: '배포 설정을 확인할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_HEALTHCHECK_FAILED]: '배포 상태 확인에 실패했습니다.',
    [ERROR_CODE.DEPLOYMENT_IDENTITY_MISMATCH]: '배포 identity가 일치하지 않습니다.',
    [ERROR_CODE.DEPLOYMENT_IMAGE_DIGEST_NOT_FOUND]: '배포 이미지 digest를 찾을 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_MANIFEST_CREATE_FAILED]: '배포 manifest를 생성할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_MANIFEST_GET_FAILED]: '배포 manifest를 조회할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_MANIFEST_LIST_FAILED]: '배포 manifest 목록을 조회할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_MANIFEST_IN_USE]: '릴리스나 스택이 참조 중인 manifest는 삭제할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_MANIFEST_NOT_FOUND]: '배포 manifest를 찾을 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_MANIFEST_VERSION_EXISTS]: '배포 manifest 버전이 이미 존재합니다.',
    [ERROR_CODE.DEPLOYMENT_NETWORK_INVALID]: '배포 네트워크가 올바르지 않습니다.',
    [ERROR_CODE.DEPLOYMENT_NETWORK_PROTECTED]: '배포 네트워크는 보호되어 변경할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_OBSERVATION_FAILED]: '배포 관찰에 실패했습니다.',
    [ERROR_CODE.DEPLOYMENT_RELEASE_CREATE_FAILED]: '배포 릴리스를 생성할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_RELEASE_FAILED]: '배포 릴리스에 실패했습니다.',
    [ERROR_CODE.DEPLOYMENT_RELEASE_GET_FAILED]: '배포 릴리스를 조회할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_RELEASE_IN_PROGRESS]: '배포 릴리스가 진행 중입니다.',
    [ERROR_CODE.DEPLOYMENT_RELEASE_LIST_FAILED]: '배포 릴리스 목록을 조회할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_RELEASE_NOT_FOUND]: '배포 릴리스를 찾을 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_RELEASE_STATE_INVALID]: '배포 릴리스 상태가 올바르지 않습니다.',
    [ERROR_CODE.DEPLOYMENT_ROLLBACK_FAILED]: '배포 롤백에 실패했습니다.',
    [ERROR_CODE.DEPLOYMENT_ROLLBACK_HEALTHCHECK_FAILED]: '배포 롤백 상태 확인에 실패했습니다.',
    [ERROR_CODE.DEPLOYMENT_ROLLBACK_ROUTE_PROBE_FAILED]: '배포 롤백 라우트 확인에 실패했습니다.',
    [ERROR_CODE.DEPLOYMENT_ROLLBACK_TARGET_UNAVAILABLE]: '배포 롤백 대상 릴리스를 사용할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_ROLLBACK_UNAVAILABLE]: '배포 롤백을 사용할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_ROUTE_PROBE_FAILED]: '배포 라우트 확인에 실패했습니다.',
    [ERROR_CODE.DEPLOYMENT_ROUTE_PROTECTED_HOSTNAME]: '배포 라우트의 호스트명은 보호되어 변경할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_SECRET_DECRYPTION_FAILED]: '배포 시크릿을 복호화할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_SECRET_IN_USE]: '배포 시크릿이 사용 중입니다.',
    [ERROR_CODE.DEPLOYMENT_SECRET_LIST_FAILED]: '배포 시크릿 목록을 조회할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_SECRET_NOT_FOUND]: '배포 시크릿을 찾을 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_SECRET_REMOVE_FAILED]: '배포 시크릿을 삭제할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_SECRET_UNRESOLVED]: '배포 시크릿을 확인할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_SECRET_UPSERT_FAILED]: '배포 시크릿을 저장할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_CREATE_FAILED]: 'compose 스택을 생성할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_DEPENDENCY_CYCLE]: 'compose 서비스 의존 관계에 순환이 있습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_DEPENDENCY_MISSING]: 'compose depends_on 대상 서비스가 없습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_IMAGE_MISSING]: 'compose 서비스에 image 가 없습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_IN_USE]: '배포가 진행 중인 스택은 삭제할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_NOT_FOUND]: 'compose 스택을 찾을 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_PARSE_FAILED]: 'compose 파일을 해석할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_PORT_MISSING]: 'compose 서비스의 컨테이너 포트를 알 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_REJECTED]: 'compose 파일에 허용하지 않는 설정이 있습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_RELEASE_ACTOR_MISSING]: '스택 배포를 시작한 계정이 없어 실행할 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_RELEASE_IN_PROGRESS]: 'compose 스택 배포가 진행 중입니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_RELEASE_NOT_FOUND]: 'compose 스택 배포를 찾을 수 없습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_SERVICES_MISSING]: 'compose 파일에 services 가 없습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_SERVICE_LIMIT]: 'compose 서비스 개수가 상한을 넘었습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_SHELL_FORM_UNSUPPORTED]: 'command 와 entrypoint 는 배열 형식만 받습니다.',
    [ERROR_CODE.DEPLOYMENT_STACK_VERSION_EXISTS]: '같은 이름과 버전의 compose 스택이 이미 있습니다.',
    [ERROR_CODE.DISK_HARD_WATERMARK]: '저장 공간 한계에 도달했습니다.',
    [ERROR_CODE.DISK_STATUS_UNAVAILABLE]: '저장 공간 상태를 확인할 수 없습니다.',
    [ERROR_CODE.DOCKER_CONFIG_MISSING]: 'Docker 설정이 없습니다.',
    [ERROR_CODE.DOCKER_LAYER_MISSING]: 'Docker 레이어를 찾을 수 없습니다.',
    [ERROR_CODE.ENGINE_LOAD_FAILED]: '이미지 로드에 실패했습니다.',
    [ERROR_CODE.ENGINE_STREAM_FAILED]: '실시간 stream을 열 수 없습니다.',
    [ERROR_CODE.ENGINE_STREAM_LIMIT]: '실시간 stream 연결 한도를 초과했습니다.',
    [ERROR_CODE.ENGINE_UNAVAILABLE]: 'Docker Engine 상태를 조회할 수 없습니다.',
    [ERROR_CODE.ENQUEUE_UNAVAILABLE]: '작업을 등록할 수 없습니다.',
    [ERROR_CODE.EXEC_TICKET_FAILED]: 'Interactive exec ticket을 생성할 수 없습니다.',
    [ERROR_CODE.EXEC_TICKET_INVALID]: 'exec ticket이 유효하지 않습니다.',
    [ERROR_CODE.FORBIDDEN]: '작업 권한이 없습니다.',
    [ERROR_CODE.IDEMPOTENCY_CONFLICT]: '동일한 요청이 이미 처리 중입니다.',
    [ERROR_CODE.IMAGE_LOAD_FAILED]: 'Docker image를 불러올 수 없습니다.',
    [ERROR_CODE.INTERNAL_ERROR]: '내부 오류가 발생했습니다.',
    [ERROR_CODE.INVALID_EMAIL_OR_PASSWORD]: '이메일 또는 비밀번호가 올바르지 않습니다.',
    [ERROR_CODE.INVITATION_BUSY]: '다른 초대 수락이 처리 중입니다.',
    [ERROR_CODE.INVITATION_INVALID]: '초대가 만료되었거나 유효하지 않습니다.',
    [ERROR_CODE.JOB_ALREADY_FINISHED]: '작업이 이미 완료되었습니다.',
    [ERROR_CODE.JOB_CANCEL_FAILED]: '작업을 취소할 수 없습니다.',
    [ERROR_CODE.JOB_CANCELLED]: '작업이 취소되었습니다.',
    [ERROR_CODE.JOB_ENQUEUE_UNAVAILABLE]: '작업을 등록할 수 없습니다.',
    [ERROR_CODE.JOB_NOT_FOUND]: '작업을 찾을 수 없습니다.',
    [ERROR_CODE.JOB_READ_FAILED]: '작업 정보를 조회할 수 없습니다.',
    [ERROR_CODE.MAINTENANCE_DRAIN_TIMEOUT]: '점검 모드 진입 대기가 초과되었습니다.',
    [ERROR_CODE.MAINTENANCE_MODE]: '점검 중입니다. 잠시 후 다시 시도해 주세요.',
    [ERROR_CODE.MAINTENANCE_READ_FAILED]: 'maintenance 상태를 조회할 수 없습니다.',
    [ERROR_CODE.MAINTENANCE_UPDATE_FAILED]: 'maintenance 상태를 변경할 수 없습니다.',
    [ERROR_CODE.MANAGEMENT_NETWORK_PROTECTED]: '관리 네트워크는 보호되어 변경할 수 없습니다.',
    [ERROR_CODE.MANAGEMENT_RESOURCE_PROTECTED]: '관리 plane 리소스는 이 경로에서 변경할 수 없습니다.',
    [ERROR_CODE.MANAGEMENT_VOLUME_PROTECTED]: '관리 볼륨은 보호되어 변경할 수 없습니다.',
    [ERROR_CODE.MIGRATION_JOURNAL_UNAVAILABLE]: '마이그레이션 저널을 사용할 수 없습니다.',
    [ERROR_CODE.NGINX_CONFIG_APPLY_FAILED]: 'Nginx 설정을 적용할 수 없습니다.',
    [ERROR_CODE.NGINX_CONFIG_CONFLICT]: 'Nginx 설정 충돌이 발생했습니다.',
    [ERROR_CODE.NGINX_CONFIG_READ_FAILED]: 'Nginx 설정을 조회할 수 없습니다.',
    [ERROR_CODE.NGINX_CONFIG_STRUCTURE_INVALID]: 'Nginx 설정 구조가 올바르지 않습니다.',
    [ERROR_CODE.NGINX_ROUTE_COLLISION]: 'Nginx 라우트가 이미 존재합니다.',
    [ERROR_CODE.NGINX_ROUTE_CREATE_FAILED]: 'Nginx 라우트를 생성할 수 없습니다.',
    [ERROR_CODE.NGINX_ROUTE_NOT_FOUND]: 'Nginx 라우트를 찾을 수 없습니다.',
    [ERROR_CODE.NGINX_ROUTE_TARGET_NOT_FOUND]: '대상 컨테이너를 찾을 수 없습니다.',
    [ERROR_CODE.NGINX_ROUTE_TARGET_UNREACHABLE]: '대상 컨테이너가 Nginx 와 같은 네트워크에 없어 연결할 수 없습니다.',
    [ERROR_CODE.NGINX_ROUTE_PROTECTED_HOSTNAME]: 'Nginx 라우트의 호스트명은 보호되어 변경할 수 없습니다.',
    [ERROR_CODE.NGINX_ROUTE_PROTECTED_TARGET]: 'Nginx 라우트의 대상은 보호되어 변경할 수 없습니다.',
    [ERROR_CODE.NGINX_ROUTE_READ_FAILED]: 'Nginx 라우트를 조회할 수 없습니다.',
    [ERROR_CODE.NGINX_ROUTE_REMOVE_FAILED]: 'Nginx 라우트를 삭제할 수 없습니다.',
    [ERROR_CODE.NGINX_UNAVAILABLE]: 'Nginx 상태를 조회할 수 없습니다.',
    [ERROR_CODE.NOTIFICATION_DESTINATION_DECRYPTION_FAILED]: '알림 대상 암호를 복호화할 수 없습니다.',
    [ERROR_CODE.NOTIFICATION_DESTINATION_ENABLED_FAILED]: '알림 대상을 활성화/비활성화할 수 없습니다.',
    [ERROR_CODE.NOTIFICATION_DESTINATION_LIST_FAILED]: '알림 대상을 조회할 수 없습니다.',
    [ERROR_CODE.NOTIFICATION_DESTINATION_NOT_FOUND]: '알림 대상을 찾을 수 없습니다.',
    [ERROR_CODE.NOTIFICATION_DESTINATION_REMOVE_FAILED]: '알림 대상을 삭제할 수 없습니다.',
    [ERROR_CODE.NOTIFICATION_DESTINATION_UPSERT_FAILED]: '알림 대상을 저장할 수 없습니다.',
    [ERROR_CODE.NOTIFICATION_TEST_FAILED]: '알림 전송 테스트에 실패했습니다.',
    [ERROR_CODE.OCI_BLOB_DIGEST_INVALID]: 'OCI blob digest가 올바르지 않습니다.',
    [ERROR_CODE.OFFSET_MISMATCH]: '업로드 offset이 일치하지 않습니다.',
    [ERROR_CODE.BOOTSTRAP_ORIGIN_FORBIDDEN]: '최초 owner 계정은 로컬 주소에서만 만들 수 있습니다.',
    [ERROR_CODE.SELF_MODIFICATION_FORBIDDEN]: '자기 자신의 계정은 변경하거나 삭제할 수 없습니다.',
    [ERROR_CODE.PRUNE_NOTHING_TO_DELETE]: '삭제할 항목이 없습니다.',
    [ERROR_CODE.PRUNE_PREVIEW_INVALID]: 'prune preview가 올바르지 않습니다.',
    [ERROR_CODE.PRUNE_PREVIEW_STALE]: 'prune preview를 다시 확인해 주세요.',
    [ERROR_CODE.PANEL_SETTING_ORIGIN_INVALID]: '공개 주소에서 hostname 을 읽을 수 없습니다.',
    [ERROR_CODE.TRUSTED_PROXY_LAST_ENTRY]: '마지막 신뢰 프록시는 삭제할 수 없습니다.',
    [ERROR_CODE.TRUSTED_PROXY_LIMIT_REACHED]: '신뢰 프록시 등록 상한에 도달했습니다.',
    [ERROR_CODE.STREAM_CLIENT_ABORTED]: '클라이언트가 스트림 연결을 종료했습니다.',
    [ERROR_CODE.STREAM_LIMIT_REACHED]: '동시 스트림 상한에 도달했습니다.',
    [ERROR_CODE.SECRET_KEY_VERSION_MISSING]: '암호화 키 버전을 찾을 수 없습니다.',
    [ERROR_CODE.SECRET_ROTATE_IN_PROGRESS]: '이미 진행 중인 키 교체 작업이 있습니다.',
    [ERROR_CODE.RECENT_AUTH_REQUIRED]: '최근 로그인이 필요한 작업입니다.',
    [ERROR_CODE.SIGN_UP_DISABLED]: '공개 가입은 허용되지 않습니다.',
    [ERROR_CODE.TRAFFIC_EXPORT_CREATE_FAILED]: '트래픽 내보내기 작업을 만들 수 없습니다.',
    [ERROR_CODE.TRAFFIC_EXPORT_DOWNLOAD_FAILED]: '내보내기 파일을 찾을 수 없습니다.',
    [ERROR_CODE.TRAFFIC_EXPORT_EXPIRED]: '내보내기가 만료되었습니다.',
    [ERROR_CODE.TRAFFIC_EXPORT_FAILED]: '트래픽 내보내기에 실패했습니다.',
    [ERROR_CODE.TRAFFIC_EXPORT_INVALID]: '내보내기 결과가 올바르지 않습니다.',
    [ERROR_CODE.TRAFFIC_EXPORT_NOT_FOUND]: '내보내기를 찾을 수 없습니다.',
    [ERROR_CODE.TRAFFIC_EXPORT_NOT_READY]: '내보내기가 아직 완료되지 않았습니다.',
    [ERROR_CODE.TRAFFIC_EXPORT_UNAVAILABLE]: '트래픽 내보내기를 사용할 수 없습니다.',
    [ERROR_CODE.TRAFFIC_STREAM_FAILED]: '실시간 트래픽을 연결할 수 없습니다.',
    [ERROR_CODE.TRAFFIC_STREAM_LIMIT]: '실시간 트래픽 연결 한도를 초과했습니다.',
    [ERROR_CODE.TRAFFIC_UNAVAILABLE]: '트래픽 집계를 조회할 수 없습니다.',
    [ERROR_CODE.UNKNOWN_ERROR]: '알 수 없는 오류가 발생했습니다.',
    [ERROR_CODE.UPLOAD_CHUNK_FAILED]: '업로드 chunk를 처리할 수 없습니다.',
    [ERROR_CODE.UPLOAD_CONCURRENCY_LIMIT]: '업로드 동시 실행 한도를 초과했습니다.',
    [ERROR_CODE.UPLOAD_FINALIZE_FAILED]: '업로드를 완료할 수 없습니다.',
    [ERROR_CODE.UPLOAD_INCOMPLETE]: '업로드가 불완전합니다.',
    [ERROR_CODE.UPLOAD_QUOTA_EXCEEDED]: '업로드 할당량을 초과했습니다.',
    [ERROR_CODE.UPLOAD_SESSION_FAILED]: '업로드 세션을 만들 수 없습니다.',
    [ERROR_CODE.UPLOAD_SESSION_INVALID]: '업로드 세션이 유효하지 않거나 만료되었습니다.',
    [ERROR_CODE.UPLOAD_SIZE_EXCEEDED]: '업로드 크기가 제한을 초과했습니다.',
    [ERROR_CODE.USER_NOT_FOUND]: '사용자를 찾을 수 없습니다.',
    [ERROR_CODE.VALIDATION_ERROR]: '요청 검증에 실패했습니다.',
}

export const ERROR_MESSAGE: Record<ErrorCode, string> = { ...ENGINE_AGENT_ERROR_MESSAGE, ...API_ERROR_MESSAGE }
