import { ENGINE_AGENT_ERROR_STATUS, splitErrorCode } from '@containers/contracts/engine-error'
import { ERROR_CODE } from './error-code'
import { ERROR_MESSAGE } from './error-message'
import type { ErrorCode } from './error-code'

export type AppError = Error & {
    code: ErrorCode
    statusCode: number
    details?: Record<string, unknown>
}

const API_STATUS_MAP = {
    API_KEY_CREATE_FAILED: 400,
    API_KEY_LIST_FAILED: 400,
    API_KEY_NOT_FOUND: 404,
    API_KEY_RATE_LIMITED: 429,
    API_KEY_REVOKE_FAILED: 400,
    ARCHIVE_ENTRY_LIMIT: 400,
    ARCHIVE_ENTRY_TYPE_INVALID: 400,
    ARCHIVE_EXPANSION_LIMIT: 400,
    ARCHIVE_INVALID: 400,
    ARCHIVE_METADATA_INVALID: 400,
    ARCHIVE_METADATA_LIMIT: 400,
    ARCHIVE_METADATA_MISSING: 400,
    ARCHIVE_PATH_INVALID: 400,
    ARTIFACT_DIGEST_MISMATCH: 400,
    ARTIFACT_IN_USE: 409,
    ARTIFACT_NOT_FOUND: 404,
    ARTIFACT_LIST_FAILED: 400,
    ARTIFACT_MEDIA_TYPE_INVALID: 400,
    ARTIFACT_NOT_READY: 409,
    AUDIT_UNAVAILABLE: 503,
    AUTH_LOCKED: 429,
    AUTH_RATE_LIMITED: 429,
    AUTH_REQUIRED: 401,
    BACKUP_CONTROL_FOREIGN_KEY_INVALID: 422,
    BACKUP_CONTROL_INVALID: 422,
    BACKUP_DIGEST_MISMATCH: 422,
    BACKUP_DISK_INSUFFICIENT: 507,
    BACKUP_ENGINE_FAILED: 422,
    BACKUP_FAILED: 422,
    BACKUP_FOREIGN_KEY_INVALID: 422,
    BACKUP_INCOMPLETE: 422,
    BACKUP_LIST_FAILED: 400,
    BACKUP_NOT_FOUND: 404,
    BACKUP_OPERATION_FAILED: 400,
    BACKUP_RESTORE_IN_PROGRESS: 409,
    BACKUP_RESTORE_ROLLBACK_FAILED: 422,
    BACKUP_SCHEMA_MISMATCH: 422,
    BACKUP_SECRET_NOT_INCLUDED: 422,
    BACKUP_SECRET_PASSPHRASE_INVALID: 422,
    BACKUP_SECRET_UNAVAILABLE: 422,
    BACKUP_TRAFFIC_CREATE_FAILED: 400,
    BACKUP_TRAFFIC_DIGEST_MISMATCH: 422,
    BACKUP_TRAFFIC_RESTORE_FAILED: 400,
    BOOTSTRAP_BUSY: 409,
    BOOTSTRAP_COMPLETE: 409,
    CHUNK_DIGEST_MISMATCH: 400,
    CHUNK_SIZE_INVALID: 400,
    CONFIRMATION_MISMATCH: 409,
    CONTAINER_INSPECT_FAILED: 503,
    CONTAINER_LOGS_FAILED: 503,
    CONTROL_FAILED: 400,
    CONTROL_PLANE_STATUS_FAILED: 400,
    DEPLOYMENT_CONFIGURATION_UNRESOLVED: 409,
    DEPLOYMENT_HEALTHCHECK_FAILED: 400,
    DEPLOYMENT_IDENTITY_MISMATCH: 409,
    DEPLOYMENT_IMAGE_DIGEST_NOT_FOUND: 409,
    DEPLOYMENT_MANIFEST_CREATE_FAILED: 400,
    DEPLOYMENT_MANIFEST_GET_FAILED: 400,
    DEPLOYMENT_MANIFEST_LIST_FAILED: 400,
    DEPLOYMENT_MANIFEST_IN_USE: 409,
    DEPLOYMENT_MANIFEST_NOT_FOUND: 404,
    DEPLOYMENT_MANIFEST_VERSION_EXISTS: 409,
    DEPLOYMENT_NETWORK_INVALID: 400,
    DEPLOYMENT_NETWORK_PROTECTED: 409,
    DEPLOYMENT_OBSERVATION_FAILED: 400,
    DEPLOYMENT_RELEASE_CREATE_FAILED: 400,
    DEPLOYMENT_RELEASE_FAILED: 400,
    DEPLOYMENT_RELEASE_GET_FAILED: 400,
    DEPLOYMENT_RELEASE_IN_PROGRESS: 409,
    DEPLOYMENT_RELEASE_LIST_FAILED: 400,
    DEPLOYMENT_RELEASE_NOT_FOUND: 404,
    DEPLOYMENT_RELEASE_STATE_INVALID: 400,
    DEPLOYMENT_ROLLBACK_FAILED: 400,
    DEPLOYMENT_ROLLBACK_HEALTHCHECK_FAILED: 400,
    DEPLOYMENT_ROLLBACK_ROUTE_PROBE_FAILED: 400,
    DEPLOYMENT_ROLLBACK_TARGET_UNAVAILABLE: 409,
    DEPLOYMENT_ROLLBACK_UNAVAILABLE: 409,
    DEPLOYMENT_ROUTE_PROBE_FAILED: 400,
    DEPLOYMENT_ROUTE_PROTECTED_HOSTNAME: 409,
    DEPLOYMENT_SECRET_DECRYPTION_FAILED: 400,
    DEPLOYMENT_SECRET_IN_USE: 409,
    DEPLOYMENT_SECRET_LIST_FAILED: 400,
    DEPLOYMENT_SECRET_NOT_FOUND: 404,
    DEPLOYMENT_SECRET_REMOVE_FAILED: 400,
    DEPLOYMENT_SECRET_UNRESOLVED: 400,
    DEPLOYMENT_SECRET_UPSERT_FAILED: 400,
    DEPLOYMENT_STACK_CREATE_FAILED: 400,
    DEPLOYMENT_STACK_DEPENDENCY_CYCLE: 400,
    DEPLOYMENT_STACK_DEPENDENCY_MISSING: 400,
    DEPLOYMENT_STACK_IMAGE_MISSING: 400,
    DEPLOYMENT_STACK_IN_USE: 409,
    DEPLOYMENT_STACK_NOT_FOUND: 404,
    DEPLOYMENT_STACK_PARSE_FAILED: 400,
    DEPLOYMENT_STACK_PORT_MISSING: 400,
    DEPLOYMENT_STACK_REJECTED: 400,
    DEPLOYMENT_STACK_RELEASE_ACTOR_MISSING: 409,
    DEPLOYMENT_STACK_RELEASE_IN_PROGRESS: 409,
    DEPLOYMENT_STACK_RELEASE_NOT_FOUND: 404,
    DEPLOYMENT_STACK_SERVICES_MISSING: 400,
    DEPLOYMENT_STACK_SERVICE_LIMIT: 400,
    DEPLOYMENT_STACK_SHELL_FORM_UNSUPPORTED: 400,
    DEPLOYMENT_STACK_VERSION_EXISTS: 409,
    DISK_HARD_WATERMARK: 507,
    DISK_STATUS_UNAVAILABLE: 503,
    DOCKER_CONFIG_MISSING: 400,
    DOCKER_LAYER_MISSING: 400,
    EGRESS_BROKER_UNAVAILABLE: 503,
    EGRESS_DELIVERY_FAILED: 502,
    EGRESS_TARGET_BLOCKED: 422,
    ENGINE_LOAD_FAILED: 400,
    ENGINE_STREAM_FAILED: 503,
    ENGINE_STREAM_LIMIT: 429,
    ENGINE_UNAVAILABLE: 503,
    ENQUEUE_UNAVAILABLE: 503,
    EXEC_TICKET_FAILED: 400,
    EXEC_TICKET_INVALID: 400,
    FORBIDDEN: 403,
    IDEMPOTENCY_CONFLICT: 409,
    IMAGE_LOAD_FAILED: 400,
    INTERNAL_ERROR: 500,
    INVALID_EMAIL_OR_PASSWORD: 401,
    INVITATION_BUSY: 409,
    INVITATION_INVALID: 410,
    JOB_ALREADY_FINISHED: 409,
    JOB_CANCEL_FAILED: 400,
    JOB_CANCELLED: 409,
    JOB_ENQUEUE_UNAVAILABLE: 503,
    JOB_NOT_FOUND: 404,
    JOB_READ_FAILED: 400,
    MAINTENANCE_DRAIN_TIMEOUT: 409,
    MAINTENANCE_MODE: 503,
    MAINTENANCE_READ_FAILED: 400,
    MAINTENANCE_UPDATE_FAILED: 400,
    MANAGEMENT_NETWORK_PROTECTED: 409,
    MANAGEMENT_RESOURCE_PROTECTED: 409,
    MANAGEMENT_VOLUME_PROTECTED: 409,
    MIGRATION_JOURNAL_UNAVAILABLE: 503,
    NGINX_CONFIG_APPLY_FAILED: 400,
    NGINX_CONFIG_CONFLICT: 409,
    NGINX_CONFIG_READ_FAILED: 400,
    NGINX_CONFIG_STRUCTURE_INVALID: 400,
    NGINX_ROUTE_COLLISION: 409,
    NGINX_ROUTE_CREATE_FAILED: 400,
    NGINX_ROUTE_NOT_FOUND: 404,
    NGINX_ROUTE_PROTECTED_HOSTNAME: 409,
    NGINX_ROUTE_TARGET_NOT_FOUND: 400,
    NGINX_ROUTE_TARGET_UNREACHABLE: 400,
    NGINX_ROUTE_PROTECTED_TARGET: 409,
    NGINX_ROUTE_READ_FAILED: 400,
    NGINX_ROUTE_REMOVE_FAILED: 400,
    NGINX_UNAVAILABLE: 503,
    NOTIFICATION_DESTINATION_DECRYPTION_FAILED: 500,
    NOTIFICATION_DESTINATION_ENABLED_FAILED: 400,
    NOTIFICATION_DESTINATION_LIST_FAILED: 400,
    NOTIFICATION_DESTINATION_NOT_FOUND: 404,
    NOTIFICATION_DESTINATION_REMOVE_FAILED: 400,
    NOTIFICATION_DESTINATION_UPSERT_FAILED: 400,
    NOTIFICATION_TEST_FAILED: 400,
    OCI_BLOB_DIGEST_INVALID: 400,
    OFFSET_MISMATCH: 409,
    BOOTSTRAP_ORIGIN_FORBIDDEN: 403,
    SELF_MODIFICATION_FORBIDDEN: 409,
    PRUNE_NOTHING_TO_DELETE: 409,
    PRUNE_PREVIEW_INVALID: 409,
    PRUNE_PREVIEW_STALE: 409,
    PANEL_SETTING_ORIGIN_INVALID: 400,
    TRUSTED_PROXY_LAST_ENTRY: 400,
    TRUSTED_PROXY_LIMIT_REACHED: 400,
    STREAM_CLIENT_ABORTED: 499,
    STREAM_LIMIT_REACHED: 429,
    SECRET_KEY_VERSION_MISSING: 500,
    SECRET_ROTATE_IN_PROGRESS: 409,
    SIGN_UP_DISABLED: 404,
    TRAFFIC_EXPORT_CREATE_FAILED: 400,
    TRAFFIC_EXPORT_DOWNLOAD_FAILED: 404,
    TRAFFIC_EXPORT_EXPIRED: 404,
    TRAFFIC_EXPORT_FAILED: 400,
    TRAFFIC_EXPORT_INVALID: 400,
    TRAFFIC_EXPORT_NOT_FOUND: 404,
    TRAFFIC_EXPORT_NOT_READY: 409,
    TRAFFIC_EXPORT_UNAVAILABLE: 503,
    TRAFFIC_STREAM_FAILED: 503,
    TRAFFIC_STREAM_LIMIT: 429,
    TRAFFIC_UNAVAILABLE: 503,
    UNKNOWN_ERROR: 500,
    UPLOAD_CHUNK_FAILED: 400,
    UPLOAD_CONCURRENCY_LIMIT: 409,
    UPLOAD_FINALIZE_FAILED: 400,
    UPLOAD_INCOMPLETE: 400,
    UPLOAD_QUOTA_EXCEEDED: 507,
    UPLOAD_SESSION_FAILED: 400,
    UPLOAD_SESSION_INVALID: 410,
    UPLOAD_SIZE_EXCEEDED: 400,
    USER_NOT_FOUND: 404,
    VALIDATION_ERROR: 400,
}

export const STATUS_MAP: Record<ErrorCode, number> = { ...ENGINE_AGENT_ERROR_STATUS, ...API_STATUS_MAP }

export const getStatusCode = (code: ErrorCode): number => STATUS_MAP[code]

export const resolveErrorCode = (rawCode: string): { code: ErrorCode; detail: string | undefined } => {
    if (rawCode in STATUS_MAP) {
        return { code: rawCode as ErrorCode, detail: undefined }
    }

    const { code, detail } = splitErrorCode(rawCode)
    return code in STATUS_MAP ? { code: code as ErrorCode, detail } : { code: ERROR_CODE.INTERNAL_ERROR, detail: undefined }
}

export const createAppError = (code: string, cause?: unknown, details?: Record<string, unknown>): AppError => {
    const error = new Error(code, cause === undefined ? undefined : { cause }) as AppError
    const resolved = resolveErrorCode(code)
    const resolvedDetails = resolved.detail === undefined ? details : { detail: resolved.detail, ...details }

    error.code = resolved.code
    error.statusCode = STATUS_MAP[resolved.code]
    if (resolvedDetails !== undefined) {
        error.details = resolvedDetails
    }

    return error
}

export const isAppError = (error: unknown): error is AppError =>
    typeof error === 'object' &&
    error !== null &&
    'code' in error &&
    'message' in error &&
    'statusCode' in error &&
    typeof error.statusCode === 'number'

export type { ErrorCode }
export { ERROR_CODE, ERROR_MESSAGE }
