import { ERROR_CODE, type ErrorCode } from './error-code'

export const ERROR_MESSAGE: Record<ErrorCode, string> = {
    [ERROR_CODE.ARTIFACT_PATH_INVALID]: 'artifact 경로가 올바르지 않습니다.',
    [ERROR_CODE.BUILD_CACHE_PRUNE_FAILED]: '빌드 캐시를 정리할 수 없습니다.',
    [ERROR_CODE.CONFIRMATION_MISMATCH]: '대상 확인 문자열이 일치하지 않습니다.',
    [ERROR_CODE.CONTAINER_CHANGES_FAILED]: '컨테이너 변경 사항을 조회할 수 없습니다.',
    [ERROR_CODE.CONTAINER_INSPECT_FAILED]: '컨테이너 상세 상태를 조회할 수 없습니다.',
    [ERROR_CODE.CONTAINER_LOGS_FAILED]: '컨테이너 로그를 조회할 수 없습니다.',
    [ERROR_CODE.CONTAINER_NAME_INVALID]: '컨테이너 이름이 올바르지 않습니다.',
    [ERROR_CODE.CONTAINER_NOT_RUNNING]: '컨테이너가 실행 중이 아닙니다.',
    [ERROR_CODE.CONTAINER_PROBE_FAILED]: '컨테이너 상태 확인에 실패했습니다.',
    [ERROR_CODE.CONTAINER_TOP_FAILED]: '컨테이너 프로세스 목록을 조회할 수 없습니다.',
    [ERROR_CODE.CONTAINER_WAIT_FAILED]: '컨테이너 대기를 완료할 수 없습니다.',
    [ERROR_CODE.CONTROL_FAILED]: 'Docker 작업을 완료할 수 없습니다.',
    [ERROR_CODE.DOCKER_NOT_FOUND]: 'Docker 리소스를 찾을 수 없습니다.',
    [ERROR_CODE.ENGINE_STREAM_LIMIT]: '실시간 stream 연결 한도를 초과했습니다.',
    [ERROR_CODE.EXEC_FAILED]: '컨테이너 명령 실행에 실패했습니다.',
    [ERROR_CODE.EXEC_SESSION_LIMIT_REACHED]: '동시 exec 세션 한도에 도달했습니다.',
    [ERROR_CODE.EXEC_TICKET_INVALID]: 'exec ticket이 유효하지 않습니다.',
    [ERROR_CODE.IMAGE_IMPACT_FAILED]: '이미지 삭제 영향도를 조회할 수 없습니다.',
    [ERROR_CODE.IMAGE_LOAD_FAILED]: 'Docker image를 불러올 수 없습니다.',
    [ERROR_CODE.IMAGE_PULL_FAILED]: 'Docker image를 내려받을 수 없습니다.',
    [ERROR_CODE.IMAGE_TAG_FAILED]: '이미지 태그를 지정할 수 없습니다.',
    [ERROR_CODE.INTERNAL_ERROR]: '내부 오류가 발생했습니다.',
    [ERROR_CODE.MANAGEMENT_NETWORK_PROTECTED]: '관리 네트워크는 보호되어 변경할 수 없습니다.',
    [ERROR_CODE.MANAGEMENT_RESOURCE_PROTECTED]: '관리 plane 리소스는 이 경로에서 변경할 수 없습니다.',
    [ERROR_CODE.MANAGEMENT_VOLUME_PROTECTED]: '관리 볼륨은 보호되어 변경할 수 없습니다.',
    [ERROR_CODE.NETWORK_CONNECT_FAILED]: '컨테이너를 네트워크에 연결할 수 없습니다.',
    [ERROR_CODE.NETWORK_DISCONNECT_FAILED]: '컨테이너를 네트워크에서 분리할 수 없습니다.',
    [ERROR_CODE.NGINX_CONFIG_CONFLICT]: 'Nginx 설정 충돌이 발생했습니다.',
    [ERROR_CODE.NGINX_CONFIG_INVALID]: 'Nginx 설정 검증에 실패했습니다.',
    [ERROR_CODE.NGINX_CONFIG_READ_FAILED]: 'Nginx 설정을 조회할 수 없습니다.',
    [ERROR_CODE.NGINX_CONTAINER_UNAVAILABLE]: 'Nginx 컨테이너를 사용할 수 없습니다.',
    [ERROR_CODE.NGINX_POST_RELOAD_PROBE_FAILED]: 'Nginx 재로드 후 상태 확인에 실패했습니다.',
    [ERROR_CODE.NGINX_PROTECTED_CONTRACT]: '관리 plane에서 보호하는 Nginx 계약을 변경할 수 없습니다.',
    [ERROR_CODE.PRUNE_PREVIEW_FAILED]: 'prune preview를 조회할 수 없습니다.',
    [ERROR_CODE.REGISTRY_CREDENTIAL_DECRYPTION_FAILED]: '레지스트리 자격 증명을 복호화할 수 없습니다.',
    [ERROR_CODE.REGISTRY_CREDENTIAL_FAILED]: '레지스트리 자격 증명 작업을 완료할 수 없습니다.',
    [ERROR_CODE.REGISTRY_CREDENTIAL_NOT_FOUND]: '레지스트리 자격 증명을 찾을 수 없습니다.',
    [ERROR_CODE.REGISTRY_CREDENTIAL_SERVICE_UNAVAILABLE]: '레지스트리 자격 증명 서비스를 사용할 수 없습니다.',
    [ERROR_CODE.REGISTRY_CREDENTIAL_STORE_INVALID]: '레지스트리 자격 증명 저장소가 올바르지 않습니다.',
    [ERROR_CODE.REGISTRY_HOST_INTERNAL]: '내부 레지스트리 호스트는 사용할 수 없습니다.',
    [ERROR_CODE.REGISTRY_HOST_MISMATCH]: '레지스트리 호스트가 일치하지 않습니다.',
    [ERROR_CODE.REGISTRY_RESOLVE_FAILED]: '레지스트리 호스트를 확인할 수 없습니다.',
    [ERROR_CODE.UNAUTHORIZED]: '인증이 필요합니다.',
}
