export const ERROR_CODE = {
    EGRESS_DELIVERY_FAILED: 'EGRESS_DELIVERY_FAILED',
    EGRESS_TARGET_BLOCKED: 'EGRESS_TARGET_BLOCKED',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE]
